sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t kujjwal02/docker-react -f Dockerfile.dev .

scripts:
  - docker run kujjwal02/docker-react npm run test -- --coverage
